### ISSUE TITLE
SAML configuration

### ISSUE THREAD

**Issue by kdbeckman** [szemek/teamcity-saml#4]
Do you have an example of what should be configured for ACS URL?

**Comment by jaiganeshvazhkudai** [comment]
+1

**Comment by pdspicer** [comment]
We were able to get it working by setting the ACS URL to the same value as the TeamCity base url. It looks like this plugin is implemented as a custom HTTP Authentication Module, and when multiple authentication modules are enabled, they are tried successively from the "main" application URL (which is the base url) until either one succeeds or they all fail, which is why the same URL should be used for SAML callbacks/ACS.

So if your teamcity base url is: https://teamcity.example.com then your ACS URL should also be https://teamcity.example.com

**Comment by kdbeckman** [comment]
Thanks.  That worked,
